张量的结构类似于 [Numpy](https://numpy.org/)中的ndarrays，而张量可以运行在GPU及其他相似的硬件加速器上。 事实上，为了减少数据的拷贝，张量和NumPy arrays在底层常常共享同一块内存(`bridge-to-np-label`{.interpreted-text role=”ref”})。 在自动微分(automatic differentiation)的过程中也使用张量进行优化(在后续[Autograd](autogradqs_tutorial.html)章节可以看到更多有关内容)。 如果已经对ndarrays十分熟悉了，那对张量的API也可以运用自如。如果还不熟悉，下面的教程会帮助你上手。

In [15]:
import torch
import numpy as np

In [16]:
# 初始化张量, 会自动推断类型

data = [[1,2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [17]:
# 使用numpy创建

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [18]:
# 使用已有张量创建

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones}\n")

x_zeros = torch.zeros_like(x_data)
print(f"Ones Tensor:\n {x_zeros}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor\n {x_rand}\n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Ones Tensor:
 tensor([[0, 0],
        [0, 0]])

Random Tensor
 tensor([[0.0061, 0.4514],
        [0.4546, 0.2737]])



In [19]:
# 通过随机或者常量创建

shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("Random Tensor")
print(rand_tensor)
print("Ones Tensor")
print(ones_tensor)
print("Zeros Tensor")
print(zeros_tensor)

Random Tensor
tensor([[0.0792, 0.8633, 0.9912],
        [0.8487, 0.0218, 0.2914]])
Ones Tensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [20]:
# 张量的属性保存了其形状，数据类型，以及其存储设备类型。

tensor = torch.rand(3, 4)

print(f"shape of tensor           : {tensor.shape}")
print(f"datatype of tensor        : {tensor.dtype}")
print(f"device tensor is stored on: {tensor.device}")
tensor = tensor.to("cuda")
print(f"\nnow the tensor is moved to cuda.")
print(f"device tensor is stored on: {tensor.device}")

shape of tensor           : torch.Size([3, 4])
datatype of tensor        : torch.float32
device tensor is stored on: cpu

now the tensor is moved to cuda.
device tensor is stored on: cuda:0


In [21]:
# 张量操作

t = torch.arange(1000).reshape(50,-1)
print(t.shape)
if torch.cuda.is_available():
    t = t.to("cuda")

print(t.device)

torch.Size([50, 20])
cuda:0


In [22]:
tensor = torch.ones(4, 4)

print(f"First row: {tensor[0]}")
print(f"First col: {tensor[:, 0]}")
print(f"last col: {tensor[:, -1]}")

tensor[:, 0] = 0

print(tensor)

First row: tensor([1., 1., 1., 1.])
First col: tensor([1., 1., 1., 1.])
last col: tensor([1., 1., 1., 1.])
tensor([[0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.]])


In [23]:
# concat

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.],
        [0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.],
        [0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.],
        [0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.]])


In [24]:
# 运筹操作

tensor = torch.randint(4, (2,2))

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.ones_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(tensor, y1, y2, y3, sep='\n')

tensor([[0, 1],
        [1, 0]])
tensor([[1, 0],
        [0, 1]])
tensor([[1, 0],
        [0, 1]])
tensor([[1, 0],
        [0, 1]])


In [25]:
# 单个元素的张量 在聚合运算场景中，你可能会得到一个单元素的张量，
# 可使用`item()`将其传唤为Python数值。

agg = tensor.sum()
print(agg, type(agg))
agg_item = agg.item()
print(agg_item, type(agg_item))


tensor(2) <class 'torch.Tensor'>
2 <class 'int'>


In [33]:
# 原地操作 修改张量中的原值操作称为原地操作。它们以 _ 后缀表示。
# 例如：x.copy_(y)，x.t_()，会改变 x。

tensor = torch.arange(12).reshape(3, 4)
print(tensor)

tensor.add_(5)
print(tensor)

t2 = torch.randint(1, 12, (3, 4))
print(t2)

tensor.copy_(t2)
print(tensor, t2, sep='\n')
print(id(tensor), id(t2))



tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
tensor([[ 1, 10, 11,  7],
        [ 3,  5, 10, 11],
        [ 2,  2,  7,  1]])
tensor([[ 1, 10, 11,  7],
        [ 3,  5, 10, 11],
        [ 2,  2,  7,  1]])
tensor([[ 1, 10, 11,  7],
        [ 3,  5, 10, 11],
        [ 2,  2,  7,  1]])
133619809470976 133619809478416


In [34]:
# 张量在使用CPU时，可与NumPy arrays共享内存空间，修改其中一个
# 会同步映射到另一个上。

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
# 对于张量的修改体现到了NumPy array上。

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [39]:
# Numpy array 转换为张量

n = np.ones(5)
t = torch.from_numpy(n)

print(n, type(n))
print(t, type(t))

np.add(n, 1, out=n)
print(n, type(n))
print(t, type(t))


[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>
[2. 2. 2. 2. 2.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.], dtype=torch.float64) <class 'torch.Tensor'>
